project:
  name: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'

info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: '@project.description@'
    version: '@project.version@'

application:
  title: ${project.name}
  version: ${project.version}

spring:
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLE:always}
  banner:
    charset: "${SPRING_BANNER_CHARSET:UTF-8}"
    location: "${SPRING_BANNER_LOCATION:classpath:/banner.txt}"


  #Configuracao do ORM (Hibernate)
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    show-sql: ${JPA_SHOW_SQL:true} #Opcao para apresentar a execucao de SQL no projeto.
    generate-ddl: ${JPA_GENERATE_DDL:true} #Cria DDDL (Crias a instrucoes de criacao/alteracao de tabela)
    hibernate:
      ddl-auto: update

  # Configuracao do banco de dados
  datasource:
    driver-class-name: ${DS_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${DS_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DS_USER:sa}
    password: ${DS_PASSWORD:}
  h2:
    console:
      enable: true
      path: /h2-console

  logging:
    level:
      br.edu.ipog.backend3.app:${NIVEL_LOG_WEB:trace}
      org.springframework.web:${NIVEL_LOG_WEB:debug}
    org:
        hibernate:
          #orm.jdbc.bind:${NIVEL_LOG_DB:info}
          SQL:${NIVEL_LOG_DB:info}
          type:${NIVEL_LOG_DB:trace}
    pattern:
      console:"%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
      file:"%d{dd-MM-yyyy HH:mm:ss}[%thread] %-5level %logger{36} - %msg%n"